name: Feature Request 
description: Request a feature or suggest us what is in your mind!
title: "[Feature]: "
labels: "Issue:feature"
assignees:
  - <project manager> 
body:
  - type: markdown
    attributes:
      value: |
        Please explain what is in your mind, we would like to hear it from you! 🤠
      
      
  - type: textarea
    id: explaining
    attributes:
      label: So, what is it about?
      description: Please describe what you're requesting for.
      placeholder: It's about...
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/DarkNinja15/sync_sphere/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct 
          required: true
